# Generated by Django 5.2.15 on 2026-06-21 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kanji_entry",
            fields=[
                ("kanji_id", models.AutoField(primary_key=True, serialize=False)),
                ("stroke_count", models.IntegerField()),
                ("jlpt_level", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Kanji_meaning",
            fields=[
                (
                    "kanji_meaning_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("meaning", models.CharField(max_length=100)),
                (
                    "kanji_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.kanji_entry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kanji_reading",
            fields=[
                (
                    "kanji_reading_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "reading_type",
                    models.CharField(
                        choices=[("onyomi", "Onyomi"), ("kunyomi", "Kunyomi")],
                        max_length=10,
                    ),
                ),
                ("reading", models.CharField(max_length=50)),
                (
                    "kanji_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.kanji_entry",
                    ),
                ),
            ],
        ),
    ]
