# Generated by Django 5.2.15 on 2026-06-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kanji_reading",
            name="kanji_id",
        ),
        migrations.DeleteModel(
            name="Kanji_meaning",
        ),
        migrations.DeleteModel(
            name="Kanji_entry",
        ),
        migrations.DeleteModel(
            name="Kanji_reading",
        ),
    ]
