# Generated by Django 5.2.15 on 2026-06-21 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "dictionary",
            "0002_remove_kanji_reading_kanji_id_delete_kanji_meaning_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Kanji_entry",
            fields=[
                ("kanji_id", models.AutoField(primary_key=True, serialize=False)),
                ("kanji", models.CharField(max_length=1, unique=True)),
                ("stroke_count", models.PositiveSmallIntegerField()),
                ("jlpt_level", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Kanji_meaning",
            fields=[
                (
                    "kanji_meaning_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("meaning", models.CharField(max_length=255)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "kanji_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meanings",
                        to="dictionary.kanji_entry",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kanji_entry", "meaning"), name="unique_kanji_meaning"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Kanji_reading",
            fields=[
                (
                    "kanji_reading_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "reading_type",
                    models.CharField(
                        choices=[("onyomi", "Onyomi"), ("kunyomi", "Kunyomi")],
                        max_length=10,
                    ),
                ),
                ("reading", models.CharField(max_length=50)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "kanji_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="dictionary.kanji_entry",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kanji_entry", "reading_type", "reading"),
                        name="unique_kanji_reading",
                    )
                ],
            },
        ),
    ]
