# Generated by Django 5.2.15 on 2026-06-22 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vocab_entry",
            fields=[
                ("vocab_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Vocab_meaning",
            fields=[
                (
                    "vocab_meaning_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("meaning", models.CharField(max_length=255)),
                (
                    "vocab_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meanings",
                        to="dictionary.vocab_entry",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vocab_entry", "meaning"), name="unique_vocab_meaning"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Vocab_writting",
            fields=[
                (
                    "vocab_writting_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "writting_type",
                    models.CharField(
                        choices=[("kanji", "Kanji"), ("kana", "Kana")], max_length=10
                    ),
                ),
                ("writting", models.CharField(max_length=255)),
                (
                    "vocab_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writtings",
                        to="dictionary.vocab_entry",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vocab_entry", "writting", "writting_type"),
                        name="unique_vocab_writting",
                    )
                ],
            },
        ),
    ]
