# Generated by Django 5.2.15 on 2026-06-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0005_alter_vocab_meaning_meaning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kanji_entry",
            name="kanji",
            field=models.CharField(db_index=True, max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name="kanji_meaning",
            name="meaning",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="kanji_reading",
            name="reading",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="vocab_meaning",
            name="meaning",
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="vocab_writting",
            name="writting",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
