# Generated by Django 5.2.15 on 2026-06-26 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dictionary",
            "0006_alter_kanji_entry_kanji_alter_kanji_meaning_meaning_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Grammar_entry",
            fields=[
                ("grammar_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "grammar",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("formation", models.CharField(blank=True, max_length=255, null=True)),
                ("meaning", models.CharField(db_index=True, max_length=512)),
                ("jlpt_level", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Grammar_example",
            fields=[
                (
                    "grammar_example_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("example_japanses", models.TextField(blank=True, null=True)),
                ("example_romaji", models.TextField(blank=True, null=True)),
                ("example_english", models.TextField(blank=True, null=True)),
                (
                    "grammar_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="dictionary.grammar_entry",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "grammar_entry",
                            "example_japanses",
                            "example_romaji",
                            "example_english",
                        ),
                        name="unique_grammar_example",
                    )
                ],
            },
        ),
    ]
