# Generated by Django 5.2.15 on 2026-06-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0007_grammar_entry_grammar_example"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="grammar_example",
            name="unique_grammar_example",
        ),
        migrations.RenameField(
            model_name="grammar_example",
            old_name="example_japanses",
            new_name="example_japanese",
        ),
        migrations.AddConstraint(
            model_name="grammar_example",
            constraint=models.UniqueConstraint(
                fields=(
                    "grammar_entry",
                    "example_japanese",
                    "example_romaji",
                    "example_english",
                ),
                name="unique_grammar_example",
            ),
        ),
    ]
