# Generated by Django 5.2.15 on 2026-08-02 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0008_remove_grammar_example_unique_grammar_example_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grammar_meaning",
            fields=[
                (
                    "grammar_meaning_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "lang",
                    models.CharField(
                        blank=True,
                        choices=[("en", "English"), ("vi", "Vietnamese")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("meaning", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Kanji_sino_vietnamese",
            fields=[
                (
                    "kanji_sino_vietnamese_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("sino_vietnamese", models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Vocab_gloss",
            fields=[
                ("vocab_gloss_id", models.AutoField(primary_key=True, serialize=False)),
                ("gloss", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vocab_sense",
            fields=[
                ("vocab_sense_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "part_of_speech",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "lang",
                    models.CharField(
                        blank=True,
                        choices=[("en", "English"), ("vi", "Vietnamese")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("applied_to_kanji", models.CharField(default="*", max_length=100)),
                ("applied_to_kana", models.CharField(default="*", max_length=100)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="grammar_example",
            name="unique_grammar_example",
        ),
        migrations.AddField(
            model_name="grammar_example",
            name="example_gloss",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grammar_example",
            name="lang",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("vi", "Vietnamese")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kanji_entry",
            name="pen_stroke",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="kanji_entry",
            name="radicals",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="kanji_meaning",
            name="lang",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("vi", "Vietnamese")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vocab_entry",
            name="jlpt_level",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vocab_writting",
            name="common",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="grammar_example",
            constraint=models.UniqueConstraint(
                fields=("grammar_entry", "example_japanese", "lang"),
                name="unique_grammar_example",
            ),
        ),
        migrations.AddField(
            model_name="grammar_meaning",
            name="grammar_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meanings",
                to="dictionary.grammar_entry",
            ),
        ),
        migrations.AddField(
            model_name="kanji_sino_vietnamese",
            name="kanji_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sino_vietnamese",
                to="dictionary.kanji_entry",
            ),
        ),
        migrations.AddField(
            model_name="vocab_sense",
            name="vocab_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="senses",
                to="dictionary.vocab_entry",
            ),
        ),
        migrations.AddField(
            model_name="vocab_gloss",
            name="vocab_sense",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grosses",
                to="dictionary.vocab_sense",
            ),
        ),
        migrations.AddConstraint(
            model_name="grammar_meaning",
            constraint=models.UniqueConstraint(
                fields=("grammar_entry", "meaning", "lang"),
                name="unique_grammar_meaning",
            ),
        ),
        migrations.AddConstraint(
            model_name="kanji_sino_vietnamese",
            constraint=models.UniqueConstraint(
                fields=("kanji_entry", "sino_vietnamese"),
                name="unique_kanji_sino_vietnamese",
            ),
        ),
        migrations.AddConstraint(
            model_name="vocab_sense",
            constraint=models.UniqueConstraint(
                fields=("vocab_entry", "position", "lang"), name="unique_vocab_sense"
            ),
        ),
        migrations.AddConstraint(
            model_name="vocab_gloss",
            constraint=models.UniqueConstraint(
                fields=("vocab_sense", "gloss"), name="unique_vocab_gloss"
            ),
        ),
    ]
