# Generated by Django 5.2.15 on 2026-08-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dictionary",
            "0009_grammar_meaning_kanji_sino_vietnamese_vocab_gloss_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grammar_entry",
            name="meaning",
        ),
        migrations.RemoveField(
            model_name="grammar_example",
            name="example_english",
        ),
        migrations.AlterField(
            model_name="grammar_entry",
            name="jlpt_level",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="kanji_entry",
            name="jlpt_level",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vocab_entry",
            name="jlpt_level",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Vocab_meaning",
        ),
    ]
