# Generated by Django 5.2.15 on 2026-08-03 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0011_remove_vocab_gloss_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vocab_meaning",
            fields=[
                (
                    "vocab_meaning_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("meaning", models.TextField(blank=True, null=True)),
                (
                    "vocab_sense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meanings",
                        to="dictionary.vocab_sense",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Vocab_gloss",
        ),
    ]
