# Generated by Django 5.2.15 on 2026-07-03 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dictionary", "0008_remove_grammar_example_unique_grammar_example_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Flash_card_set",
            fields=[
                (
                    "flash_card_set_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flash_card_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flash_card_entry",
            fields=[
                ("flash_card_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("kanji", "Kanji"),
                            ("vocab", "Vocab"),
                            ("grammar", "Grammar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "flash_card_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flash_cards",
                        to="learning.flash_card_set",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grammar_flash_card",
            fields=[
                (
                    "flash_card_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="grammar_flash_card",
                        serialize=False,
                        to="learning.flash_card_entry",
                    ),
                ),
                (
                    "grammar_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grammar_flash_cards",
                        to="dictionary.grammar_entry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kanji_flash_card",
            fields=[
                (
                    "flash_card_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="kanji_flash_card",
                        serialize=False,
                        to="learning.flash_card_entry",
                    ),
                ),
                (
                    "kanji_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kanji_flash_cards",
                        to="dictionary.kanji_entry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vocab_flash_card",
            fields=[
                (
                    "flash_card_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="vocab_flash_card",
                        serialize=False,
                        to="learning.flash_card_entry",
                    ),
                ),
                (
                    "vocab_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocab_flash_cards",
                        to="dictionary.vocab_entry",
                    ),
                ),
            ],
        ),
    ]
