# Generated by Django 5.2.15 on 2026-07-04 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0008_remove_grammar_example_unique_grammar_example_and_more"),
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flash_card_set",
            name="owner_id",
        ),
        migrations.AddField(
            model_name="flash_card_set",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flash_card_sets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="grammar_flash_card",
            name="flash_card_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="grammar_flash_card",
                serialize=False,
                to="learning.flash_card_entry",
            ),
        ),
        migrations.AlterField(
            model_name="grammar_flash_card",
            name="grammar_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grammar_flash_cards",
                to="dictionary.grammar_entry",
            ),
        ),
        migrations.AlterField(
            model_name="kanji_flash_card",
            name="flash_card_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="kanji_flash_card",
                serialize=False,
                to="learning.flash_card_entry",
            ),
        ),
        migrations.AlterField(
            model_name="kanji_flash_card",
            name="kanji_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kanji_flash_cards",
                to="dictionary.kanji_entry",
            ),
        ),
        migrations.AlterField(
            model_name="vocab_flash_card",
            name="flash_card_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="vocab_flash_card",
                serialize=False,
                to="learning.flash_card_entry",
            ),
        ),
        migrations.AlterField(
            model_name="vocab_flash_card",
            name="vocab_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vocab_flash_cards",
                to="dictionary.vocab_entry",
            ),
        ),
    ]
