# Generated by Django 5.2.15 on 2026-07-04 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "learning",
            "0002_remove_flash_card_set_owner_id_flash_card_set_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="grammar_flash_card",
            name="flash_card_entry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="grammar_flash_card",
                serialize=False,
                to="learning.flash_card_entry",
            ),
        ),
        migrations.AlterField(
            model_name="kanji_flash_card",
            name="flash_card_entry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="kanji_flash_card",
                serialize=False,
                to="learning.flash_card_entry",
            ),
        ),
        migrations.AlterField(
            model_name="vocab_flash_card",
            name="flash_card_entry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="vocab_flash_card",
                serialize=False,
                to="learning.flash_card_entry",
            ),
        ),
    ]
