# Generated by Django 5.2.15 on 2026-07-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_alter_grammar_flash_card_flash_card_entry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flash_card_set",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
