# Generated by Django 5.2.15 on 2026-07-18 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_flash_card_set_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forgotten_flash_card",
            fields=[
                (
                    "flash_card_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="forgotten_flash_card",
                        serialize=False,
                        to="learning.flash_card_entry",
                    ),
                ),
                ("forgotten_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Remebered_flash_card",
            fields=[
                (
                    "flash_card_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="remembered_flash_card",
                        serialize=False,
                        to="learning.flash_card_entry",
                    ),
                ),
                ("remembered_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
