# Generated by Django 5.2.15 on 2026-07-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_forgotten_flash_card_remebered_flash_card"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remebered_flash_card",
            name="flash_card_entry",
        ),
        migrations.AddField(
            model_name="flash_card_entry",
            name="status",
            field=models.CharField(
                choices=[("remembered", "Remembered"), ("forgotten", "Forgotten")],
                default="forgotten",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Forgotten_flash_card",
        ),
        migrations.DeleteModel(
            name="Remebered_flash_card",
        ),
    ]
