import { createContext, useCallback, useContext, useEffect, useState } from "react"

const LanguageContext = createContext(null)

const vietnamese = {
  "Explore": "Khám phá",
  "Dictionary": "Từ điển",
  "Learning": "Học tập",
  "Log in": "Đăng nhập",
  "Logout": "Đăng xuất",
  "Log out": "Đăng xuất",
  "Register": "Đăng ký",
  "Collapse navigation": "Thu gọn điều hướng",
  "Expand navigation": "Mở rộng điều hướng",
  "Search": "Tìm kiếm",
  "vocab": "từ vựng",
  "grammar": "ngữ pháp",
  "kanji": "kanji",
  "Master Japanese with focused practice.": "Làm chủ tiếng Nhật bằng phương pháp luyện tập tập trung.",
  "Forge your Japanese.": "Rèn luyện tiếng Nhật.",
  "Search reliable language references, build personal flashcard sets, and prepare for the JLPT one deliberate session at a time.": "Tra cứu tài liệu ngôn ngữ đáng tin cậy, xây dựng bộ thẻ ghi nhớ cá nhân và chuẩn bị cho JLPT qua từng buổi học có mục tiêu.",
  "Start learning": "Bắt đầu học",
  "Explore vocabulary": "Khám phá từ vựng",
  "Open dictionary": "Mở từ điển",
  "Dictionary at a glance": "Tổng quan từ điển",
  "Dictionary Page": "Trang từ điển",
  "No dictionary entries found for": "Không tìm thấy mục từ điển cho",
  "Search results": "Kết quả tìm kiếm",
  "Back to results": "Quay lại kết quả",
  "Related vocabulary": "Từ vựng liên quan",
  "Related kanji": "Kanji liên quan",
  "Loading related entries...": "Đang tải mục liên quan...",
  "Unable to load related entries.": "Không thể tải mục liên quan.",
  "No related entries found.": "Không tìm thấy mục liên quan.",
  "Kanji · Vocabulary · Grammar · Personal flashcards": "Kanji · Từ vựng · Ngữ pháp · Thẻ ghi nhớ cá nhân",
  "Study with discipline.": "Học tập với kỷ luật.",
  "Loading...": "Đang tải...",
  "Grammar Page": "Trang ngữ pháp",
  "Kanji Page": "Trang kanji",
  "Vocabulary Page": "Trang từ vựng",
  "Quiz Page": "Trang trắc nghiệm",
  "Error occurred while searching for grammar.": "Đã xảy ra lỗi khi tìm kiếm ngữ pháp.",
  "Error occurred while searching for kanji.": "Đã xảy ra lỗi khi tìm kiếm kanji.",
  "Error occurred while searching for vocabulary.": "Đã xảy ra lỗi khi tìm kiếm từ vựng.",
  "No grammar found for": "Không tìm thấy ngữ pháp cho",
  "No kanji found for": "Không tìm thấy kanji cho",
  "No words found for": "Không tìm thấy từ vựng cho",
  "Previous": "Trước",
  "Next": "Tiếp",
  "Meaning": "Nghĩa",
  "Formation": "Cấu trúc",
  "JLPT Level": "Trình độ JLPT",
  "Examples": "Ví dụ",
  "Stroke count": "Số nét",
  "JLPT level": "Trình độ JLPT",
  "Vocabulary": "Từ vựng",
  "Grammar": "Ngữ pháp",
  "Part of speech": "Từ loại",
  "No meaning": "Không có nghĩa",
  "Flashcard": "Thẻ ghi nhớ",
  "Unsupported flashcard type": "Loại thẻ ghi nhớ không được hỗ trợ",
  "Type": "Loại",
  "Click to flip": "Nhấn để lật",
  "Show flashcard front": "Hiện mặt trước thẻ ghi nhớ",
  "Show flashcard answer": "Hiện đáp án thẻ ghi nhớ",
  "Edit Flashcard": "Sửa thẻ ghi nhớ",
  "Type your kanji/vocab/grammar term here...": "Nhập kanji/từ vựng/ngữ pháp tại đây...",
  "Selected": "Đã chọn",
  "Cancel": "Hủy",
  "Save": "Lưu",
  "All": "Tất cả",
  "Remembered": "Đã nhớ",
  "Forgotten": "Chưa nhớ",
  "All flashcards": "Tất cả thẻ ghi nhớ",
  "Remembered flashcards": "Thẻ đã nhớ",
  "Forgotten flashcards": "Thẻ chưa nhớ",
  "No flashcards in this set yet.": "Bộ này chưa có thẻ ghi nhớ.",
  "Open set →": "Mở bộ →",
  "This set has no flash cards.": "Bộ này không có thẻ ghi nhớ.",
  "Session complete": "Hoàn thành buổi học",
  "You have reviewed every flashcard in this session.": "Bạn đã ôn tập tất cả thẻ trong buổi học này.",
  "End session": "Kết thúc buổi học",
  "Restart": "Học lại",
  "Login required": "Cần đăng nhập",
  "Please log in to access your flashcard sets.": "Vui lòng đăng nhập để truy cập các bộ thẻ ghi nhớ.",
  "Please log in before creating a new flashcard set.": "Vui lòng đăng nhập trước khi tạo bộ thẻ ghi nhớ mới.",
  "Unable to load flash cards.": "Không thể tải thẻ ghi nhớ.",
  "Unable to create flashcard set.": "Không thể tạo bộ thẻ ghi nhớ.",
  "Unable to update flashcard set.": "Không thể cập nhật bộ thẻ ghi nhớ.",
  "Choose a dictionary entry first.": "Hãy chọn một mục từ điển trước.",
  "Unable to create flashcard.": "Không thể tạo thẻ ghi nhớ.",
  "Learning Session": "Buổi học",
  "End Session": "Kết thúc buổi học",
  "Loading flash cards...": "Đang tải thẻ ghi nhớ...",
  "Set name": "Tên bộ thẻ",
  "Set description": "Mô tả bộ thẻ",
  "Save Changes": "Lưu thay đổi",
  "Edit Flashcard Set": "Sửa bộ thẻ ghi nhớ",
  "Total": "Tổng cộng",
  "Practice!": "Luyện tập!",
  "Create Flashcard": "Tạo thẻ ghi nhớ",
  "Creating": "Đang tạo",
  "Saving": "Đang lưu",
  "Back to flashcard sets": "Quay lại các bộ thẻ",
  "New Flashcard": "Thẻ ghi nhớ mới",
  "My Flashcard sets": "Các bộ thẻ của tôi",
  "New Flashcard Set": "Bộ thẻ mới",
  "Name": "Tên",
  "Description": "Mô tả",
  "Submit": "Gửi",
  "Continue your JLPT practice.": "Tiếp tục luyện tập JLPT của bạn.",
  "Email": "Email",
  "Password": "Mật khẩu",
  "Logging in": "Đang đăng nhập",
  "Need an account?": "Chưa có tài khoản?",
  "Create your JLPT Fighter account.": "Tạo tài khoản JLPT Fighter của bạn.",
  "Unable to create an account with those details.": "Không thể tạo tài khoản với thông tin này.",
  "Creating account": "Đang tạo tài khoản",
  "Create account": "Tạo tài khoản",
  "Already have an account?": "Đã có tài khoản?",
  "Unable to load account": "Không thể tải tài khoản",
  "Loading profile...": "Đang tải hồ sơ...",
  "FIGHTER PROFILE": "HỒ SƠ CHIẾN BINH",
  "Member since": "Thành viên từ",
  "Flashcard sets": "Bộ thẻ ghi nhớ",
  "Active sets": "Bộ đang hoạt động",
  "Total cards": "Tổng số thẻ",
  "In your library": "Trong thư viện của bạn",
  "of all cards": "trong tổng số thẻ",
  "Review due": "Cần ôn tập",
  "Cards not remembered": "Thẻ chưa nhớ",
  "Library progress": "Tiến độ thư viện",
  "Breakdown of your": "Phân loại",
  "flashcards": "thẻ ghi nhớ của bạn",
  "CARDS": "THẺ",
  "Account": "Tài khoản",
  "LAST LOGIN": "ĐĂNG NHẬP GẦN NHẤT",
  "Logging out": "Đang đăng xuất",
  "No data": "Không có dữ liệu",
  "Authentication failed.": "Xác thực thất bại.",
  "No active account found with the given credentials": "Không tìm thấy tài khoản đang hoạt động với thông tin đăng nhập này.",
  "An unexpected error occurred": "Đã xảy ra lỗi không mong muốn",
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("eng")
  const t = useCallback((text) => language === "vi" ? vietnamese[text] ?? text : text, [language])

  useEffect(() => {
    document.documentElement.lang = language === "vi" ? "vi" : "en"
  }, [language])

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider")
  return context
}
